const MOCK_CATEGORIES = [
  { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical', display_order: 1 },
  { id: 'cat-hospitality', name: 'Hotel & Hospitality Uniforms', slug: 'hospitality', display_order: 2 },
  { id: 'cat-corporate', name: 'Corporate (Suits, Blazers, Shirts)', slug: 'corporate', display_order: 3 },
  { id: 'cat-advocate', name: 'Advocates & Legal (Coats & Gowns)', slug: 'advocate', display_order: 4 },
  { id: 'cat-school', name: 'School Uniforms', slug: 'school', display_order: 5 },
  { id: 'cat-convocation', name: 'Convocation (Gowns & Caps)', slug: 'convocation', display_order: 6 },
  { id: 'cat-security', name: 'Security & Defence Uniforms', slug: 'security', display_order: 7 },
  { id: 'cat-industrial', name: 'Industrial & Factory Workwear', slug: 'industrial', display_order: 8 },
  { id: 'cat-sports', name: 'Sports & PE Uniforms', slug: 'sports', display_order: 9 },
  { id: 'cat-banking', name: 'Banking & Finance Formals', slug: 'banking', display_order: 10 },
  { id: 'cat-police', name: 'Police & Paramilitary (Ceremonial)', slug: 'police', display_order: 11 },
  { id: 'cat-fire', name: 'Fire & Safety Uniforms', slug: 'fire', display_order: 12 },
  { id: 'cat-airline', name: 'Airline & Aviation Crew', slug: 'airline', display_order: 13 }
]

const MOCK_PRODUCTS = [
  // ═══════════════════════════════════════════
  // ── MEDICAL & HEALTHCARE (10 products) ──
  // ═══════════════════════════════════════════
  {
    id: 'prod-doctor-male',
    name: "Premium Men's Professional Lab Coat",
    description: "Classic full-length men's professional lab coat featuring a tailored chest fit, side vent openings for pocket access, multiple utility pockets, and durable reinforced stitching. Anti-microbial treated.",
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Premium%20Men's%20Professional%20Lab%20Coat.%20Classic%20full-length%20men's%20professional%20lab%20coat%20featuring%20a%20tailored%20chest%20fit%2C%20side%20vent%20openings%20for%20pocket%20access%2C%20multiple%20utility%20pockets%2C%20and%20durable%20reinforced%20stitching.%20Anti-microbial%20treated.?width=800&height=600&nologo=true&seed=42"],
    fabric: '100% Cotton with Liquid Barrier Finish',
    is_featured: true,
    is_visible: true,
    price_range: '₹450 - ₹650',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Light Blue', 'Navy Blue'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 100000).toISOString(),
  },
  {
    id: 'prod-doctor-female',
    name: "Premium Women's Tailored Lab Coat",
    description: "Princess-seamed women's professional lab coat featuring a slim, elegant tailored fit, side pocket access, chest utility pocket, and anti-wrinkle fabric.",
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Premium%20Women's%20Tailored%20Lab%20Coat.%20Princess-seamed%20women's%20professional%20lab%20coat%20featuring%20a%20slim%2C%20elegant%20tailored%20fit%2C%20side%20pocket%20access%2C%20chest%20utility%20pocket%2C%20and%20anti-wrinkle%20fabric.?width=800&height=600&nologo=true&seed=42"],
    fabric: '100% Cotton with Liquid Barrier Finish',
    is_featured: true,
    is_visible: true,
    price_range: '₹450 - ₹650',
    min_order_qty: 50,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Light Blue', 'Soft Pink'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 150000).toISOString(),
  },
  {
    id: 'prod-doctor-2',
    name: 'Premium Hospital Unisex OT Scrub Suit',
    description: 'Classic medical scrubs set (top and cargo trousers) featuring double chest pockets and drawstring waist. Antimicrobial treated for surgical and general ward duty.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Premium%20Hospital%20Unisex%20OT%20Scrub%20Suit.%20Classic%20medical%20scrubs%20set%20(top%20and%20cargo%20trousers)%20featuring%20double%20chest%20pockets%20and%20drawstring%20waist.%20Antimicrobial%20treated%20for%20surgical%20and%20general%20ward%20duty.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Breathable Poly-Cotton Medical Weave',
    is_featured: false,
    is_visible: true,
    price_range: '₹480 - ₹690',
    min_order_qty: 100,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Green', 'Teal', 'Navy Blue', 'Maroon'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 200000).toISOString(),
  },
  {
    id: 'prod-nurse-1',
    name: 'Premium Nurse Tunic Uniform (Zip Front)',
    description: 'Professional nursing tunic featuring elegant contrast piping, zip front closure, dual deep side pockets, and back action pleats for high flexibility during duty.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Premium%20Nurse%20Tunic%20Uniform%20(Zip%20Front).%20Professional%20nursing%20tunic%20featuring%20elegant%20contrast%20piping%2C%20zip%20front%20closure%2C%20dual%20deep%20side%20pockets%2C%20and%20back%20action%20pleats%20for%20high%20flexibility%20during%20duty.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Poly-Cotton Easy-Care Poplin',
    is_featured: true,
    is_visible: true,
    price_range: '₹420 - ₹580',
    min_order_qty: 100,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy Blue', 'Burgundy', 'Teal'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 400000).toISOString(),
  },
  {
    id: 'prod-nurse-2',
    name: 'Female V-Neck Patient Care Scrub Set',
    description: 'Lightweight scrubs designed for nurses, dental assistants, and clinic care teams. Soft touch, fade-resistant fabric with 4-way stretch utility.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Female%20V-Neck%20Patient%20Care%20Scrub%20Set.%20Lightweight%20scrubs%20designed%20for%20nurses%2C%20dental%20assistants%2C%20and%20clinic%20care%20teams.%20Soft%20touch%2C%20fade-resistant%20fabric%20with%204-way%20stretch%20utility.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Stretchable Poly-Rayon Blend',
    is_featured: false,
    is_visible: true,
    price_range: '₹450 - ₹600',
    min_order_qty: 80,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ceil Blue', 'Wine', 'Hunter Green'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 550000).toISOString(),
  },
  {
    id: 'prod-patient-1',
    name: 'Premium Patient Hospital Gown (Unisex)',
    description: 'Comfortable and breathable patient gown featuring a classic back-tie closure and roomy sleeves. Lightweight fabric ensures maximum comfort during extended hospital stays.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Premium%20Patient%20Hospital%20Gown%20(Unisex).%20Comfortable%20and%20breathable%20patient%20gown%20featuring%20a%20classic%20back-tie%20closure%20and%20roomy%20sleeves.%20Lightweight%20fabric%20ensures%20maximum%20comfort%20during%20extended%20hospital%20stays.?width=800&height=600&nologo=true&seed=42"],
    fabric: '100% Breathable Soft Cotton',
    is_featured: true,
    is_visible: true,
    price_range: '₹180 - ₹280',
    min_order_qty: 100,
    sizes: ['Free Size', 'L', 'XL'],
    colors: ['Light Blue', 'White', 'Green'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 550000).toISOString(),
  },
  {
    id: 'prod-patient-2',
    name: 'Disposable Sterile SMS Patient Gown',
    description: 'Single-use fluid-resistant sterile patient gown designed for surgical and diagnostic prep. Lightweight SMS barrier fabric provides hygienic protection.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Disposable%20Sterile%20SMS%20Patient%20Gown.%20Single-use%20fluid-resistant%20sterile%20patient%20gown%20designed%20for%20surgical%20and%20diagnostic%20prep.%20Lightweight%20SMS%20barrier%20fabric%20provides%20hygienic%20protection.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Fluid-Resistant SMS Non-Woven',
    is_featured: false,
    is_visible: true,
    price_range: '₹90 - ₹140',
    min_order_qty: 250,
    sizes: ['Free Size'],
    colors: ['Blue', 'Green'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 580000).toISOString(),
  },
  {
    id: 'prod-medical-apron',
    name: 'Surgical Disposable Wraparound Apron',
    description: 'Fluid-proof wraparound surgical apron for theatre, autopsy, and clinical procedures. Neck-tie and waist-tie adjustable fit with full torso coverage.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Surgical%20Disposable%20Wraparound%20Apron.%20Fluid-proof%20wraparound%20surgical%20apron%20for%20theatre%2C%20autopsy%2C%20and%20clinical%20procedures.%20Neck-tie%20and%20waist-tie%20adjustable%20fit%20with%20full%20torso%20coverage.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Waterproof PE Laminated Non-Woven',
    is_featured: false,
    is_visible: true,
    price_range: '₹45 - ₹80',
    min_order_qty: 500,
    sizes: ['Free Size'],
    colors: ['Blue', 'White'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 610000).toISOString(),
  },
  {
    id: 'prod-medical-cap',
    name: 'Disposable Surgeon Bouffant Cap (Pack of 100)',
    description: 'Breathable non-woven bouffant caps with elastic band. Ideal for operation theatres, pharmaceutical labs, and food processing units.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Disposable%20Surgeon%20Bouffant%20Cap%20(Pack%20of%20100).%20Breathable%20non-woven%20bouffant%20caps%20with%20elastic%20band.%20Ideal%20for%20operation%20theatres%2C%20pharmaceutical%20labs%2C%20and%20food%20processing%20units.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Spunbond Polypropylene Non-Woven',
    is_featured: false,
    is_visible: true,
    price_range: '₹250 - ₹350',
    min_order_qty: 100,
    sizes: ['Free Size'],
    colors: ['Blue', 'Green', 'White'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 620000).toISOString(),
  },
  {
    id: 'prod-medical-shoe',
    name: 'Disposable Anti-Skid Shoe Cover (Pack of 50)',
    description: 'Fluid-resistant shoe covers with anti-skid sole grip. Essential for OT, ICU, pharmaceutical clean rooms, and lab environments.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Disposable%20Anti-Skid%20Shoe%20Cover%20(Pack%20of%2050).%20Fluid-resistant%20shoe%20covers%20with%20anti-skid%20sole%20grip.%20Essential%20for%20OT%2C%20ICU%2C%20pharmaceutical%20clean%20rooms%2C%20and%20lab%20environments.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'CPE Waterproof Film',
    is_featured: false,
    is_visible: true,
    price_range: '₹180 - ₹250',
    min_order_qty: 200,
    sizes: ['Free Size'],
    colors: ['Blue', 'White'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 630000).toISOString(),
  },
  {
    id: 'prod-scrub-jogger',
    name: 'Unisex Premium Jogger Scrub Set',
    description: 'Modern athletic fit scrub set featuring moisture-wicking 4-way stretch fabric, ribbed knit collar, jogger pants with elastic ankle cuffs, and 6 functional utility pockets.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Unisex%20Premium%20Jogger%20Scrub%20Set.%20Modern%20athletic%20fit%20scrub%20set%20featuring%20moisture-wicking%204-way%20stretch%20fabric%2C%20ribbed%20knit%20collar%2C%20jogger%20pants%20with%20elastic%20ankle%20cuffs%2C%20and%206%20functional%20utility%20pockets.?width=800&height=600&nologo=true&seed=42"],
    fabric: '4-Way Stretch Polyester-Spandex Blend',
    is_featured: true,
    is_visible: true,
    price_range: '₹750 - ₹950',
    min_order_qty: 80,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Teal', 'Navy Blue', 'Ceil Blue', 'Charcoal Grey'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 635000).toISOString(),
  },
  {
    id: 'prod-scrub-pediatric',
    name: 'Pediatric Specialist Printed Scrub Top',
    description: 'Friendly, printed pediatric scrub top featuring cute cartoon characters, stethoscopes, and animal illustrations. Helps put young patients at ease during clinical visits.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Pediatric%20Specialist%20Printed%20Scrub%20Top.%20Friendly%2C%20printed%20pediatric%20scrub%20top%20featuring%20cute%20cartoon%20characters%2C%20stethoscopes%2C%20and%20animal%20illustrations.%20Helps%20put%20young%20patients%20at%20ease%20during%20clinical%20visits.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Soft-Touch Breathable Cotton-Blend',
    is_featured: false,
    is_visible: true,
    price_range: '₹320 - ₹450',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Light Blue Print', 'Pink Print', 'Mint Print'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 640000).toISOString(),
  },
  {
    id: 'prod-tunic-dentist',
    name: 'Dentist & Specialist Clinic Wrap Tunic',
    description: 'Ergonomic wrap-style tunic with asymmetrical side button closure, mock neck, and twin hip pockets. Designed for dentists, dermatologists, and aesthetic clinic staff.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Dentist%20%26%20Specialist%20Clinic%20Wrap%20Tunic.%20Ergonomic%20wrap-style%20tunic%20with%20asymmetrical%20side%20button%20closure%2C%20mock%20neck%2C%20and%20twin%20hip%20pockets.%20Designed%20for%20dentists%2C%20dermatologists%2C%20and%20aesthetic%20clinic%20staff.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Stain-Resistant Cotton-Poly Drill',
    is_featured: true,
    is_visible: true,
    price_range: '₹490 - ₹690',
    min_order_qty: 50,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Pristine White', 'Lilac', 'Mint Green'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 645000).toISOString(),
  },
  {
    id: 'prod-staff-wardboy',
    name: 'Hospital Ward Attendant & Staff Uniform Set',
    description: 'High-durability utility uniform consisting of a short-sleeve comfort tunic and straight-fit cargo pants. Designed for ward boys, hospital helper staff, and stretcher attendants.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Hospital%20Ward%20Attendant%20%26%20Staff%20Uniform%20Set.%20High-durability%20utility%20uniform%20consisting%20of%20a%20short-sleeve%20comfort%20tunic%20and%20straight-fit%20cargo%20pants.%20Designed%20for%20ward%20boys%2C%20hospital%20helper%20staff%2C%20and%20stretcher%20attendants.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Heavy-Duty Industrial Poly-Cotton',
    is_featured: false,
    is_visible: true,
    price_range: '₹380 - ₹520',
    min_order_qty: 100,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy Blue', 'Slate Grey', 'Olive Green'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 650000).toISOString(),
  },
  {
    id: 'prod-gown-isolation',
    name: 'Autoclavable Surgical Isolation Gown',
    description: 'Reusable surgical isolation gown with full back overlap, stockinette cuffs, and tie closures. Constructed to withstand frequent autoclave sterilization cycles.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Autoclavable%20Surgical%20Isolation%20Gown.%20Reusable%20surgical%20isolation%20gown%20with%20full%20back%20overlap%2C%20stockinette%20cuffs%2C%20and%20tie%20closures.%20Constructed%20to%20withstand%20frequent%20autoclave%20sterilization%20cycles.?width=800&height=600&nologo=true&seed=42"],
    fabric: '100% Cotton Canvas with Liquid Barrier',
    is_featured: false,
    is_visible: true,
    price_range: '₹280 - ₹380',
    min_order_qty: 100,
    sizes: ['Free Size'],
    colors: ['Surgical Green', 'Sky Blue'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 655000).toISOString(),
  },
  {
    id: 'prod-doctor-blazer',
    name: 'Premium Medical Consultation Blazer',
    description: 'Tailored short consultation coat for senior doctors and medical consultants. Features elegant notch lapels, structured shoulders, and clean lining.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Premium%20Medical%20Consultation%20Blazer.%20Tailored%20short%20consultation%20coat%20for%20senior%20doctors%20and%20medical%20consultants.%20Features%20elegant%20notch%20lapels%2C%20structured%20shoulders%2C%20and%20clean%20lining.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Premium Tropical Poly-Viscose',
    is_featured: true,
    is_visible: true,
    price_range: '₹950 - ₹1,400',
    min_order_qty: 30,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Charcoal Grey', 'Navy Blue'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 660000).toISOString(),
  },
  {
    id: 'prod-maternity-scrub',
    name: 'Maternity Comfort Scrub Top',
    description: 'Specially tailored maternity scrub top with side-panel stretch panels and adjustable drawstrings, allowing comfort and room to grow throughout pregnancy.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Maternity%20Comfort%20Scrub%20Top.%20Specially%20tailored%20maternity%20scrub%20top%20with%20side-panel%20stretch%20panels%20and%20adjustable%20drawstrings%2C%20allowing%20comfort%20and%20room%20to%20grow%20throughout%20pregnancy.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Super Soft Bamboo-Cotton Blend',
    is_featured: false,
    is_visible: true,
    price_range: '₹480 - ₹620',
    min_order_qty: 30,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Royal Blue', 'Ceil Blue', 'Burgundy'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 665000).toISOString(),
  },
  {
    id: 'prod-patient-pajama',
    name: 'Premium Two-Piece Patient Suit',
    description: 'Deluxe patient uniform including a front-buttoned short-sleeve shirt and matching elastic waist trousers. Offers dignity and comfort for long-term recovery stays.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Premium%20Two-Piece%20Patient%20Suit.%20Deluxe%20patient%20uniform%20including%20a%20front-buttoned%20short-sleeve%20shirt%20and%20matching%20elastic%20waist%20trousers.%20Offers%20dignity%20and%20comfort%20for%20long-term%20recovery%20stays.?width=800&height=600&nologo=true&seed=42"],
    fabric: '100% Soft Combed Cotton (Hospital Grade)',
    is_featured: false,
    is_visible: true,
    price_range: '₹320 - ₹480',
    min_order_qty: 100,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue Striped', 'Green Patterned', 'Solid White'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 670000).toISOString(),
  },
  {
    id: 'prod-medical-lab-apron',
    name: 'Pharmacist Short Sleeve Lab Jacket',
    description: 'Professional waist-length lab jacket featuring short sleeves, three patch pockets, and snap-button front. Perfect for pharmacists, lab technicians, and lab assistants.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Pharmacist%20Short%20Sleeve%20Lab%20Jacket.%20Professional%20waist-length%20lab%20jacket%20featuring%20short%20sleeves%2C%20three%20patch%20pockets%2C%20and%20snap-button%20front.%20Perfect%20for%20pharmacists%2C%20lab%20technicians%2C%20and%20lab%20assistants.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Durable Twill Poplin',
    is_featured: false,
    is_visible: true,
    price_range: '₹290 - ₹390',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Light Grey'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 675000).toISOString(),
  },
  {
    id: 'prod-scrub-premium-fit',
    name: 'Elite Stretch V-Neck Scrub Suit',
    description: 'Designer-grade athletic scrub suit with yoga-style waistband, clean V-neck, mesh lining for breathability, and zip pockets. Antimicrobial and wrinkle-free.',
    category_id: 'cat-medical',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Elite%20Stretch%20V-Neck%20Scrub%20Suit.%20Designer-grade%20athletic%20scrub%20suit%20with%20yoga-style%20waistband%2C%20clean%20V-neck%2C%20mesh%20lining%20for%20breathability%2C%20and%20zip%20pockets.%20Antimicrobial%20and%20wrinkle-free.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Elite Rayon-Poly-Spandex Blend',
    is_featured: true,
    is_visible: true,
    price_range: '₹890 - ₹1,190',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Olive', 'Royal Blue', 'Steel Grey'],
    categories: { id: 'cat-medical', name: 'Healthcare & Hospital Uniforms', slug: 'medical' },
    created_at: new Date(Date.now() - 680000).toISOString(),
  },

  // ═══════════════════════════════════════════
  // ── HOSPITALITY & HOUSEKEEPING (10 products) ──
  // ═══════════════════════════════════════════
  {
    id: 'prod-chef-1',
    name: 'Double-Breasted Master Chef Jacket',
    description: 'Elite hospitality chef coat designed for hot kitchen environments. Features breathable mesh underarms, a thermometer arm pocket, and reversible front closure.',
    category_id: 'cat-hospitality',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Double-Breasted%20Master%20Chef%20Jacket.%20Elite%20hospitality%20chef%20coat%20designed%20for%20hot%20kitchen%20environments.%20Features%20breathable%20mesh%20underarms%2C%20a%20thermometer%20arm%20pocket%2C%20and%20reversible%20front%20closure.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Heavy Duty Canvas Cotton with Breathable Mesh',
    is_featured: true,
    is_visible: true,
    price_range: '₹750 - ₹1,100',
    min_order_qty: 30,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Grey'],
    categories: { id: 'cat-hospitality', name: 'Hotel & Hospitality Uniforms', slug: 'hospitality' },
    created_at: new Date(Date.now() - 800000).toISOString(),
  },
  {
    id: 'prod-chef-2',
    name: 'Premium Chef Kitchen Bib Apron',
    description: 'Professional kitchen bib apron tailored from stain-resistant canvas twill. Features dual deep pockets, reinforced loops, and adjustable neck straps.',
    category_id: 'cat-hospitality',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Premium%20Chef%20Kitchen%20Bib%20Apron.%20Professional%20kitchen%20bib%20apron%20tailored%20from%20stain-resistant%20canvas%20twill.%20Features%20dual%20deep%20pockets%2C%20reinforced%20loops%2C%20and%20adjustable%20neck%20straps.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Stain-Resistant Cotton Canvas Twill',
    is_featured: false,
    is_visible: true,
    price_range: '₹180 - ₹260',
    min_order_qty: 100,
    sizes: ['Free Size'],
    colors: ['Black', 'Brown', 'Navy', 'Denim Blue'],
    categories: { id: 'cat-hospitality', name: 'Hotel & Hospitality Uniforms', slug: 'hospitality' },
    created_at: new Date(Date.now() - 820000).toISOString(),
  },
  {
    id: 'prod-chef-pants',
    name: 'Chef Check Baggy Trouser',
    description: 'Classic houndstooth check chef trouser with elastic drawstring waist. Loose-fit for comfortable kitchen movement. Industrial wash-safe and colour-fast.',
    category_id: 'cat-hospitality',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Chef%20Check%20Baggy%20Trouser.%20Classic%20houndstooth%20check%20chef%20trouser%20with%20elastic%20drawstring%20waist.%20Loose-fit%20for%20comfortable%20kitchen%20movement.%20Industrial%20wash-safe%20and%20colour-fast.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Poly-Cotton Twill with Check Pattern',
    is_featured: false,
    is_visible: true,
    price_range: '₹320 - ₹480',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Black & White Check', 'Black', 'Grey'],
    categories: { id: 'cat-hospitality', name: 'Hotel & Hospitality Uniforms', slug: 'hospitality' },
    created_at: new Date(Date.now() - 830000).toISOString(),
  },
  {
    id: 'prod-chef-hat',
    name: 'Tall Pleated Chef Toque Hat',
    description: 'Traditional tall white chef toque with adjustable velcro band. Pleated design with internal mesh lining for ventilation.',
    category_id: 'cat-hospitality',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Tall%20Pleated%20Chef%20Toque%20Hat.%20Traditional%20tall%20white%20chef%20toque%20with%20adjustable%20velcro%20band.%20Pleated%20design%20with%20internal%20mesh%20lining%20for%20ventilation.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Starched Poly-Cotton with Mesh Lining',
    is_featured: false,
    is_visible: true,
    price_range: '₹120 - ₹200',
    min_order_qty: 50,
    sizes: ['Free Size'],
    colors: ['White', 'Black'],
    categories: { id: 'cat-hospitality', name: 'Hotel & Hospitality Uniforms', slug: 'hospitality' },
    created_at: new Date(Date.now() - 840000).toISOString(),
  },
  {
    id: 'prod-waiter-1',
    name: 'Waiter Formal Vest & Bow Tie Set',
    description: 'Classic five-button waistcoat with adjustable back buckle and matching bow tie. Designed for dining banquets and executive bar staff.',
    category_id: 'cat-hospitality',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Waiter%20Formal%20Vest%20%26%20Bow%20Tie%20Set.%20Classic%20five-button%20waistcoat%20with%20adjustable%20back%20buckle%20and%20matching%20bow%20tie.%20Designed%20for%20dining%20banquets%20and%20executive%20bar%20staff.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Poly-Viscose Gabardine with Satin Back',
    is_featured: true,
    is_visible: true,
    price_range: '₹650 - ₹900',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Charcoal Grey', 'Maroon'],
    categories: { id: 'cat-hospitality', name: 'Hotel & Hospitality Uniforms', slug: 'hospitality' },
    created_at: new Date(Date.now() - 1000000).toISOString(),
  },
  {
    id: 'prod-waiter-shirt',
    name: 'Formal Waiter Long-Sleeve Service Shirt',
    description: 'Crisp formal shirt tailored for waiters, bartenders, and front-of-house staff. Features reinforced cuffs, chest pocket, and wrinkle-resistant finish.',
    category_id: 'cat-hospitality',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Formal%20Waiter%20Long-Sleeve%20Service%20Shirt.%20Crisp%20formal%20shirt%20tailored%20for%20waiters%2C%20bartenders%2C%20and%20front-of-house%20staff.%20Features%20reinforced%20cuffs%2C%20chest%20pocket%2C%20and%20wrinkle-resistant%20finish.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Easy-Iron Poly-Cotton Poplin',
    is_featured: false,
    is_visible: true,
    price_range: '₹350 - ₹500',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Light Blue', 'Cream'],
    categories: { id: 'cat-hospitality', name: 'Hotel & Hospitality Uniforms', slug: 'hospitality' },
    created_at: new Date(Date.now() - 980000).toISOString(),
  },


  // ═══════════════════════════════════════════
  // ── CORPORATE WEAR (8 products) ──
  // ═══════════════════════════════════════════
  {
    id: 'prod-corporate-1',
    name: "Slim Fit Corporate Men's Blazer",
    description: 'Ultra-modern corporate wool-blend blazer with double vent, notch lapel, and customized satin lining. Ideal for corporate office environments.',
    category_id: 'cat-corporate',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Slim%20Fit%20Corporate%20Men's%20Blazer.%20Ultra-modern%20corporate%20wool-blend%20blazer%20with%20double%20vent%2C%20notch%20lapel%2C%20and%20customized%20satin%20lining.%20Ideal%20for%20corporate%20office%20environments.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Premium Tropical Wool Blend',
    is_featured: true,
    is_visible: true,
    price_range: '₹1,800 - ₹2,400',
    min_order_qty: 50,
    sizes: ['36', '38', '40', '42', '44', '46'],
    colors: ['Navy Blue', 'Charcoal', 'Black'],
    categories: { id: 'cat-corporate', name: 'Corporate (Suits, Blazers, Shirts)', slug: 'corporate' },
    created_at: new Date(Date.now() - 1100000).toISOString(),
  },
  {
    id: 'prod-corporate-women-blazer',
    name: "Women's Tailored Corporate Blazer",
    description: 'Single-breasted feminine blazer with princess seam, padded shoulders, and functional pockets. Perfect for front-office, banking, and airline staff.',
    category_id: 'cat-corporate',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Women's%20Tailored%20Corporate%20Blazer.%20Single-breasted%20feminine%20blazer%20with%20princess%20seam%2C%20padded%20shoulders%2C%20and%20functional%20pockets.%20Perfect%20for%20front-office%2C%20banking%2C%20and%20airline%20staff.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Premium Poly-Viscose Suiting',
    is_featured: true,
    is_visible: true,
    price_range: '₹1,600 - ₹2,200',
    min_order_qty: 50,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Navy Blue', 'Black', 'Charcoal'],
    categories: { id: 'cat-corporate', name: 'Corporate (Suits, Blazers, Shirts)', slug: 'corporate' },
    created_at: new Date(Date.now() - 1120000).toISOString(),
  },
  {
    id: 'prod-corporate-2',
    name: 'Tailored Poly-Wool Corporate Nehru Jacket',
    description: 'Modern corporate sleeveless Modi waistcoat featuring traditional mandarin collar and high-quality button closures. Gives security or front office teams a premium identity.',
    category_id: 'cat-corporate',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Tailored%20Poly-Wool%20Corporate%20Nehru%20Jacket.%20Modern%20corporate%20sleeveless%20Modi%20waistcoat%20featuring%20traditional%20mandarin%20collar%20and%20high-quality%20button%20closures.%20Gives%20security%20or%20front%20office%20teams%20a%20premium%20identity.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Premium Poly-Wool Tweed Weave',
    is_featured: false,
    is_visible: true,
    price_range: '₹850 - ₹1,200',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal Grey', 'Black', 'Beige'],
    categories: { id: 'cat-corporate', name: 'Corporate (Suits, Blazers, Shirts)', slug: 'corporate' },
    created_at: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: 'prod-corporate-3',
    name: 'Premium Corporate Oxford Shirt',
    description: 'Classic Oxford button-down shirt. Wrinkle-free finish with reinforced collar stays. Ideal for daily corporate and banking wear.',
    category_id: 'cat-corporate',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Premium%20Corporate%20Oxford%20Shirt.%20Classic%20Oxford%20button-down%20shirt.%20Wrinkle-free%20finish%20with%20reinforced%20collar%20stays.%20Ideal%20for%20daily%20corporate%20and%20banking%20wear.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Egyptian Cotton Oxford Weave',
    is_featured: false,
    is_visible: true,
    price_range: '₹480 - ₹700',
    min_order_qty: 55,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Light Blue', 'Grey', 'Sky Blue Stripe'],
    categories: { id: 'cat-corporate', name: 'Corporate (Suits, Blazers, Shirts)', slug: 'corporate' },
    created_at: new Date(Date.now() - 1300000).toISOString(),
  },
  {
    id: 'prod-corporate-trouser',
    name: 'Corporate Formal Flat-Front Trouser',
    description: 'Classic flat-front formal trouser with permanent crease, hook-bar closure, and belt loops. Machine washable with shape-retention fabric.',
    category_id: 'cat-corporate',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Corporate%20Formal%20Flat-Front%20Trouser.%20Classic%20flat-front%20formal%20trouser%20with%20permanent%20crease%2C%20hook-bar%20closure%2C%20and%20belt%20loops.%20Machine%20washable%20with%20shape-retention%20fabric.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Premium Poly-Viscose Suiting',
    is_featured: false,
    is_visible: true,
    price_range: '₹550 - ₹850',
    min_order_qty: 50,
    sizes: ['28', '30', '32', '34', '36', '38', '40', '42'],
    colors: ['Navy Blue', 'Black', 'Charcoal', 'Khaki'],
    categories: { id: 'cat-corporate', name: 'Corporate (Suits, Blazers, Shirts)', slug: 'corporate' },
    created_at: new Date(Date.now() - 1310000).toISOString(),
  },
  {
    id: 'prod-corporate-tie',
    name: 'Corporate Silk Necktie & Pocket Square Set',
    description: 'Premium woven silk tie with matching pocket square. Available in solid, stripe, and micro-dot patterns. Custom logo printing available for bulk orders.',
    category_id: 'cat-corporate',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Corporate%20Silk%20Necktie%20%26%20Pocket%20Square%20Set.%20Premium%20woven%20silk%20tie%20with%20matching%20pocket%20square.%20Available%20in%20solid%2C%20stripe%2C%20and%20micro-dot%20patterns.%20Custom%20logo%20printing%20available%20for%20bulk%20orders.?width=800&height=600&nologo=true&seed=42"],
    fabric: '100% Woven Silk',
    is_featured: false,
    is_visible: true,
    price_range: '₹350 - ₹600',
    min_order_qty: 50,
    sizes: ['Standard (148 cm)'],
    colors: ['Navy Blue', 'Maroon', 'Black', 'Royal Blue'],
    categories: { id: 'cat-corporate', name: 'Corporate (Suits, Blazers, Shirts)', slug: 'corporate' },
    created_at: new Date(Date.now() - 1320000).toISOString(),
  },
  {
    id: 'prod-corporate-polo',
    name: 'Corporate Branded Polo T-Shirt',
    description: 'Relaxed-fit corporate polo with ribbed collar, 3-button placket, and side vents. Perfect for casual Fridays, tech teams, and field staff. Custom logo embroidery included.',
    category_id: 'cat-corporate',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Corporate%20Branded%20Polo%20T-Shirt.%20Relaxed-fit%20corporate%20polo%20with%20ribbed%20collar%2C%203-button%20placket%2C%20and%20side%20vents.%20Perfect%20for%20casual%20Fridays%2C%20tech%20teams%2C%20and%20field%20staff.%20Custom%20logo%20embroidery%20included.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Honeycomb Knit Lacoste Cotton',
    is_featured: true,
    is_visible: true,
    price_range: '₹280 - ₹420',
    min_order_qty: 100,
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['White', 'Navy Blue', 'Black', 'Red', 'Grey'],
    categories: { id: 'cat-corporate', name: 'Corporate (Suits, Blazers, Shirts)', slug: 'corporate' },
    created_at: new Date(Date.now() - 1330000).toISOString(),
  },
  {
    id: 'prod-corporate-suit',
    name: "Men's 2-Piece Executive Suit Set",
    description: 'Complete 2-piece suit (blazer + trouser) tailored from premium tropical wool. Single-breasted, double-vent, with full canvas construction for a structured silhouette.',
    category_id: 'cat-corporate',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Men's%202-Piece%20Executive%20Suit%20Set.%20Complete%202-piece%20suit%20(blazer%20%2B%20trouser)%20tailored%20from%20premium%20tropical%20wool.%20Single-breasted%2C%20double-vent%2C%20with%20full%20canvas%20construction%20for%20a%20structured%20silhouette.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Super 120s Tropical Wool',
    is_featured: true,
    is_visible: true,
    price_range: '₹3,500 - ₹5,500',
    min_order_qty: 30,
    sizes: ['36', '38', '40', '42', '44', '46', '48'],
    colors: ['Navy Blue', 'Charcoal', 'Black', 'Mid Grey'],
    categories: { id: 'cat-corporate', name: 'Corporate (Suits, Blazers, Shirts)', slug: 'corporate' },
    created_at: new Date(Date.now() - 1080000).toISOString(),
  },

  // ═══════════════════════════════════════════
  // ── ADVOCATES & LEGAL (6 products) ──
  // ═══════════════════════════════════════════
  {
    id: 'prod-advocate-1',
    name: 'Classic Black Advocate Coat',
    description: 'Premium structured black advocate coat with notch lapel, satin-lined interior, and reinforced stitching. Tailored specifically for Indian courts — District, High Court, and Supreme Court.',
    category_id: 'cat-advocate',
    images: ['/images/advocate_coat.png'],
    fabric: 'Poly-Wool Wrinkle-Resistant Suiting',
    is_featured: true,
    is_visible: true,
    price_range: '₹1,250 - ₹1,850',
    min_order_qty: 30,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    categories: { id: 'cat-advocate', name: 'Advocates & Legal (Coats & Gowns)', slug: 'advocate' },
    created_at: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'prod-advocate-2',
    name: 'Lady Advocate Formal Black Jacket',
    description: 'Elegant structured single-breasted black jacket designed for women legal practitioners in district and High Courts. Features inner pockets and comfortable back vents.',
    category_id: 'cat-advocate',
    images: ['/images/advocate_coat.png'],
    fabric: 'Premium Tropical Wool Blend',
    is_featured: false,
    is_visible: true,
    price_range: '₹950 - ₹1,400',
    min_order_qty: 30,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black'],
    categories: { id: 'cat-advocate', name: 'Advocates & Legal (Coats & Gowns)', slug: 'advocate' },
    created_at: new Date(Date.now() - 700000).toISOString(),
  },
  {
    id: 'prod-advocate-gown',
    name: 'High Court / Supreme Court Advocate Gown',
    description: 'Full-length flowing black legal gown with pleated back, gathered shoulder yoke, and satin-trimmed front panels. Mandatory for High Court and Supreme Court appearances.',
    category_id: 'cat-advocate',
    images: ['/images/advocate_coat.png'],
    fabric: 'Premium Matte Polyester Suiting',
    is_featured: true,
    is_visible: true,
    price_range: '₹1,800 - ₹2,500',
    min_order_qty: 20,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    categories: { id: 'cat-advocate', name: 'Advocates & Legal (Coats & Gowns)', slug: 'advocate' },
    created_at: new Date(Date.now() - 640000).toISOString(),
  },
  {
    id: 'prod-advocate-band',
    name: 'Advocate White Collar Band (Set of 5)',
    description: 'Starched white cotton collar bands (bib) for advocates. Classic two-tab style as prescribed by the Bar Council of India. Sold in packs of 5.',
    category_id: 'cat-advocate',
    images: ['/images/advocate_coat.png'],
    fabric: 'Starched 100% Cotton Poplin',
    is_featured: false,
    is_visible: true,
    price_range: '₹120 - ₹180',
    min_order_qty: 100,
    sizes: ['Free Size'],
    colors: ['White'],
    categories: { id: 'cat-advocate', name: 'Advocates & Legal (Coats & Gowns)', slug: 'advocate' },
    created_at: new Date(Date.now() - 660000).toISOString(),
  },
  {
    id: 'prod-advocate-trouser',
    name: 'Advocate Formal Black Striped Trouser',
    description: 'Classic flat-front black trouser with subtle pin-stripe. Permanent crease, comfort waistband, and tailored leg for a professional courtroom appearance.',
    category_id: 'cat-advocate',
    images: ['/images/advocate_coat.png'],
    fabric: 'Poly-Wool Suiting with Stripe',
    is_featured: false,
    is_visible: true,
    price_range: '₹650 - ₹950',
    min_order_qty: 30,
    sizes: ['28', '30', '32', '34', '36', '38', '40'],
    colors: ['Black', 'Black Stripe'],
    categories: { id: 'cat-advocate', name: 'Advocates & Legal (Coats & Gowns)', slug: 'advocate' },
    created_at: new Date(Date.now() - 680000).toISOString(),
  },
  {
    id: 'prod-advocate-shirt',
    name: 'Advocate Formal White Full-Sleeve Shirt',
    description: 'Crisp white formal shirt specifically cut for wear under advocate coats. Extra-long placket, reinforced collar, and French cuff option available.',
    category_id: 'cat-advocate',
    images: ['/images/advocate_coat.png'],
    fabric: '100% Cotton Twill with Easy-Iron Finish',
    is_featured: false,
    is_visible: true,
    price_range: '₹380 - ₹550',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White'],
    categories: { id: 'cat-advocate', name: 'Advocates & Legal (Coats & Gowns)', slug: 'advocate' },
    created_at: new Date(Date.now() - 690000).toISOString(),
  },

  // ═══════════════════════════════════════════
  // ── SCHOOL UNIFORMS (10 products) ──
  // ═══════════════════════════════════════════
  {
    id: 'prod-school-1',
    name: 'Premium School Blazer (Embroidered Crest)',
    description: 'High-durability school blazer tailored from premium terry-wool fabric. Resists fading and pilling over daily wash. Custom school crest embroidery included.',
    category_id: 'cat-school',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Premium%20School%20Blazer%20(Embroidered%20Crest).%20High-durability%20school%20blazer%20tailored%20from%20premium%20terry-wool%20fabric.%20Resists%20fading%20and%20pilling%20over%20daily%20wash.%20Custom%20school%20crest%20embroidery%20included.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Terry-Wool Premium Blend',
    is_featured: true,
    is_visible: true,
    price_range: '₹850 - ₹1,200',
    min_order_qty: 100,
    sizes: ['22', '24', '26', '28', '30', '32', '34', '36', '38', '40'],
    colors: ['Navy Blue', 'Black', 'Maroon', 'Bottle Green'],
    categories: { id: 'cat-school', name: 'School Uniforms', slug: 'school' },
    created_at: new Date(Date.now() - 1400000).toISOString(),
  },
  {
    id: 'prod-school-2',
    name: 'Classic Girls Pleated Pinafore',
    description: 'Standard school pinafore featuring elegant box pleats and a side button closure. Tailored from sweat-wicking twill. Custom check pattern available.',
    category_id: 'cat-school',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Classic%20Girls%20Pleated%20Pinafore.%20Standard%20school%20pinafore%20featuring%20elegant%20box%20pleats%20and%20a%20side%20button%20closure.%20Tailored%20from%20sweat-wicking%20twill.%20Custom%20check%20pattern%20available.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Premium Polyester-Cotton Twill',
    is_featured: true,
    is_visible: true,
    price_range: '₹350 - ₹500',
    min_order_qty: 150,
    sizes: ['22', '24', '26', '28', '30', '32'],
    colors: ['Grey', 'Navy Blue', 'Brown', 'Check Pattern'],
    categories: { id: 'cat-school', name: 'School Uniforms', slug: 'school' },
    created_at: new Date(Date.now() - 1500000).toISOString(),
  },
  {
    id: 'prod-school-shirt',
    name: 'School Uniform Formal Shirt (Half / Full Sleeve)',
    description: 'Crisp white or coloured school shirt with pointed collar, chest pocket with logo embroidery, and reinforced seams. Available in both half and full sleeve.',
    category_id: 'cat-school',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20School%20Uniform%20Formal%20Shirt%20(Half%20%2F%20Full%20Sleeve).%20Crisp%20white%20or%20coloured%20school%20shirt%20with%20pointed%20collar%2C%20chest%20pocket%20with%20logo%20embroidery%2C%20and%20reinforced%20seams.%20Available%20in%20both%20half%20and%20full%20sleeve.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Premium Poly-Cotton Poplin',
    is_featured: false,
    is_visible: true,
    price_range: '₹180 - ₹280',
    min_order_qty: 200,
    sizes: ['22', '24', '26', '28', '30', '32', '34', '36', '38'],
    colors: ['White', 'Light Blue', 'Cream'],
    categories: { id: 'cat-school', name: 'School Uniforms', slug: 'school' },
    created_at: new Date(Date.now() - 1420000).toISOString(),
  },
  {
    id: 'prod-school-trouser',
    name: 'School Uniform Formal Trouser',
    description: 'Durable school trouser with elastic waist option for juniors and belt-loop for seniors. Colour-fast fabric that resists fading even after 100+ washes.',
    category_id: 'cat-school',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20School%20Uniform%20Formal%20Trouser.%20Durable%20school%20trouser%20with%20elastic%20waist%20option%20for%20juniors%20and%20belt-loop%20for%20seniors.%20Colour-fast%20fabric%20that%20resists%20fading%20even%20after%20100%2B%20washes.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Premium Poly-Cotton Drill',
    is_featured: false,
    is_visible: true,
    price_range: '₹250 - ₹400',
    min_order_qty: 200,
    sizes: ['22', '24', '26', '28', '30', '32', '34', '36', '38'],
    colors: ['Grey', 'Navy Blue', 'Black', 'Khaki'],
    categories: { id: 'cat-school', name: 'School Uniforms', slug: 'school' },
    created_at: new Date(Date.now() - 1430000).toISOString(),
  },
  {
    id: 'prod-school-tie',
    name: 'School Striped Necktie (Elastic / Regular)',
    description: 'Woven polyester school tie in house colours with diagonal stripe pattern. Available in both elastic clip-on (for juniors) and regular knot styles.',
    category_id: 'cat-school',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20School%20Striped%20Necktie%20(Elastic%20%2F%20Regular).%20Woven%20polyester%20school%20tie%20in%20house%20colours%20with%20diagonal%20stripe%20pattern.%20Available%20in%20both%20elastic%20clip-on%20(for%20juniors)%20and%20regular%20knot%20styles.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Woven Polyester Satin',
    is_featured: false,
    is_visible: true,
    price_range: '₹60 - ₹120',
    min_order_qty: 200,
    sizes: ['Junior (35 cm)', 'Senior (50 cm)'],
    colors: ['Maroon & Gold', 'Navy & Silver', 'Green & Gold', 'Custom House Colours'],
    categories: { id: 'cat-school', name: 'School Uniforms', slug: 'school' },
    created_at: new Date(Date.now() - 1440000).toISOString(),
  },
  {
    id: 'prod-school-sweater',
    name: 'School V-Neck Pullover Sweater',
    description: 'Warm acrylic-wool blend V-neck pullover with ribbed cuffs and hemband. School crest embroidery on chest. Pill-resistant and machine-washable.',
    category_id: 'cat-school',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20School%20V-Neck%20Pullover%20Sweater.%20Warm%20acrylic-wool%20blend%20V-neck%20pullover%20with%20ribbed%20cuffs%20and%20hemband.%20School%20crest%20embroidery%20on%20chest.%20Pill-resistant%20and%20machine-washable.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Acrylic-Wool Blend Knit',
    is_featured: true,
    is_visible: true,
    price_range: '₹380 - ₹550',
    min_order_qty: 100,
    sizes: ['22', '24', '26', '28', '30', '32', '34', '36', '38', '40'],
    colors: ['Navy Blue', 'Maroon', 'Grey', 'Bottle Green'],
    categories: { id: 'cat-school', name: 'School Uniforms', slug: 'school' },
    created_at: new Date(Date.now() - 1450000).toISOString(),
  },
  {
    id: 'prod-school-skirt',
    name: "Girls Pleated School Skirt (Knee-Length)",
    description: 'Classic knife-pleated school skirt with concealed side zipper and elastic waistband for comfort. Stain-resistant and easy-wash.',
    category_id: 'cat-school',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Girls%20Pleated%20School%20Skirt%20(Knee-Length).%20Classic%20knife-pleated%20school%20skirt%20with%20concealed%20side%20zipper%20and%20elastic%20waistband%20for%20comfort.%20Stain-resistant%20and%20easy-wash.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Premium Poly-Viscose Twill',
    is_featured: false,
    is_visible: true,
    price_range: '₹220 - ₹350',
    min_order_qty: 150,
    sizes: ['22', '24', '26', '28', '30', '32'],
    colors: ['Grey', 'Navy Blue', 'Check Pattern'],
    categories: { id: 'cat-school', name: 'School Uniforms', slug: 'school' },
    created_at: new Date(Date.now() - 1460000).toISOString(),
  },
  {
    id: 'prod-school-pe',
    name: 'School PE / Sports Track Suit Set',
    description: 'Comfortable sportswear track suit (jacket + track pant) with school colour accents. Moisture-wicking fabric for outdoor games and PT classes.',
    category_id: 'cat-school',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20School%20PE%20%2F%20Sports%20Track%20Suit%20Set.%20Comfortable%20sportswear%20track%20suit%20(jacket%20%2B%20track%20pant)%20with%20school%20colour%20accents.%20Moisture-wicking%20fabric%20for%20outdoor%20games%20and%20PT%20classes.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Micro-Mesh Polyester with Lycra',
    is_featured: true,
    is_visible: true,
    price_range: '₹450 - ₹700',
    min_order_qty: 100,
    sizes: ['22', '24', '26', '28', '30', '32', '34', '36', '38'],
    colors: ['Navy & White', 'Maroon & White', 'Green & Gold', 'Black & Red'],
    categories: { id: 'cat-school', name: 'School Uniforms', slug: 'school' },
    created_at: new Date(Date.now() - 1470000).toISOString(),
  },
  {
    id: 'prod-school-belt',
    name: 'School Uniform Leather Belt (Logo Buckle)',
    description: 'Genuine leather school belt with custom school-crest metal buckle. Adjustable length with pre-punched holes. Polished brass or chrome finish.',
    category_id: 'cat-school',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20School%20Uniform%20Leather%20Belt%20(Logo%20Buckle).%20Genuine%20leather%20school%20belt%20with%20custom%20school-crest%20metal%20buckle.%20Adjustable%20length%20with%20pre-punched%20holes.%20Polished%20brass%20or%20chrome%20finish.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Genuine Leather with Metal Buckle',
    is_featured: false,
    is_visible: true,
    price_range: '₹120 - ₹220',
    min_order_qty: 200,
    sizes: ['S (22-26)', 'M (28-32)', 'L (34-38)'],
    colors: ['Black', 'Brown'],
    categories: { id: 'cat-school', name: 'School Uniforms', slug: 'school' },
    created_at: new Date(Date.now() - 1480000).toISOString(),
  },
  {
    id: 'prod-school-socks',
    name: 'School Uniform Knee-High Socks (Pack of 3)',
    description: 'Premium cotton-blend school socks with reinforced heel and toe. Elastic cuff for stay-up fit. Colour-fast after 100+ washes. Pack of 3 pairs.',
    category_id: 'cat-school',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20School%20Uniform%20Knee-High%20Socks%20(Pack%20of%203).%20Premium%20cotton-blend%20school%20socks%20with%20reinforced%20heel%20and%20toe.%20Elastic%20cuff%20for%20stay-up%20fit.%20Colour-fast%20after%20100%2B%20washes.%20Pack%20of%203%20pairs.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Combed Cotton with Spandex',
    is_featured: false,
    is_visible: true,
    price_range: '₹90 - ₹150',
    min_order_qty: 500,
    sizes: ['Junior (1-3)', 'Medium (4-6)', 'Senior (7-10)'],
    colors: ['White', 'Navy Blue', 'Grey', 'Black'],
    categories: { id: 'cat-school', name: 'School Uniforms', slug: 'school' },
    created_at: new Date(Date.now() - 1490000).toISOString(),
  },

  // ═══════════════════════════════════════════
  // ── CONVOCATION & ACADEMIC (6 products) ──
  // ═══════════════════════════════════════════
  {
    id: 'prod-convocation-1',
    name: 'Premium Convocation Gown (Full-Length)',
    description: 'Elegant traditional graduation gown with back zipper, pleated sleeve details, and fluted bell sleeves. Suitable for Bachelor, Master, and Doctoral ceremonies.',
    category_id: 'cat-convocation',
    images: ['/images/category_convocation.png'],
    fabric: 'Deluxe Matte Polyester',
    is_featured: true,
    is_visible: true,
    price_range: '₹600 - ₹900',
    min_order_qty: 50,
    sizes: ['S (5\'0-5\'4)', 'M (5\'4-5\'8)', 'L (5\'8-6\'0)', 'XL (6\'0-6\'4)'],
    colors: ['Black', 'Navy Blue', 'Maroon'],
    categories: { id: 'cat-convocation', name: 'Convocation (Gowns & Caps)', slug: 'convocation' },
    created_at: new Date(Date.now() - 1520000).toISOString(),
  },
  {
    id: 'prod-convocation-2',
    name: 'Deluxe Academic Mortarboard Cap',
    description: 'Standard square academic cap featuring a sturdy elastic interior headband and custom-matched hanging tassel with year charm.',
    category_id: 'cat-convocation',
    images: ['/images/category_convocation.png'],
    fabric: 'Matte Polyester with Reinforced Board',
    is_featured: false,
    is_visible: true,
    price_range: '₹150 - ₹220',
    min_order_qty: 100,
    sizes: ['Free Size'],
    colors: ['Black', 'Navy Blue'],
    categories: { id: 'cat-convocation', name: 'Convocation (Gowns & Caps)', slug: 'convocation' },
    created_at: new Date(Date.now() - 1540000).toISOString(),
  },
  {
    id: 'prod-convocation-hood',
    name: 'Academic Stream Colour Hood',
    description: 'Satin-lined academic hood denoting the degree stream. Draped over the gown during convocation. Colour coded as per university norms — Arts (white), Science (gold), Commerce (pink), etc.',
    category_id: 'cat-convocation',
    images: ['/images/category_convocation.png'],
    fabric: 'Premium Satin-Lined Polyester',
    is_featured: true,
    is_visible: true,
    price_range: '₹250 - ₹400',
    min_order_qty: 50,
    sizes: ['Free Size'],
    colors: ['Gold (Science)', 'White (Arts)', 'Pink (Commerce)', 'Blue (Engineering)', 'Green (Medicine)'],
    categories: { id: 'cat-convocation', name: 'Convocation (Gowns & Caps)', slug: 'convocation' },
    created_at: new Date(Date.now() - 1530000).toISOString(),
  },
  {
    id: 'prod-convocation-stole',
    name: 'Graduation Honour Stole / Sash',
    description: 'Embroidered satin stole worn over the gown to denote academic honours, societies, or department affiliation. Custom text and logo embroidery available.',
    category_id: 'cat-convocation',
    images: ['/images/category_convocation.png'],
    fabric: 'Premium Satin with Embroidery',
    is_featured: false,
    is_visible: true,
    price_range: '₹200 - ₹350',
    min_order_qty: 50,
    sizes: ['Standard (72" x 5")'],
    colors: ['Gold', 'Maroon', 'Royal Blue', 'Green', 'Custom Colours'],
    categories: { id: 'cat-convocation', name: 'Convocation (Gowns & Caps)', slug: 'convocation' },
    created_at: new Date(Date.now() - 1550000).toISOString(),
  },
  {
    id: 'prod-convocation-phd',
    name: 'PhD / Doctoral Regalia Gown Set',
    description: 'Premium doctoral gown set with velvet front panels, velvet chevron sleeve bars, and 8-sided tam cap with gold bullion tassel. The ultimate academic regalia.',
    category_id: 'cat-convocation',
    images: ['/images/category_convocation.png'],
    fabric: 'Heavyweight Matte Polyester with Velvet Trim',
    is_featured: true,
    is_visible: true,
    price_range: '₹2,500 - ₹4,000',
    min_order_qty: 10,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black with Gold Trim', 'Black with Maroon Trim', 'Black with Blue Trim'],
    categories: { id: 'cat-convocation', name: 'Convocation (Gowns & Caps)', slug: 'convocation' },
    created_at: new Date(Date.now() - 1510000).toISOString(),
  },
  {
    id: 'prod-convocation-set',
    name: 'Complete Convocation Set (Gown + Cap + Hood)',
    description: 'All-in-one convocation bundle — includes full-length gown, mortarboard cap with tassel, and stream-coloured hood. Best value combo for university bulk orders.',
    category_id: 'cat-convocation',
    images: ['/images/category_convocation.png'],
    fabric: 'Deluxe Matte Polyester',
    is_featured: true,
    is_visible: true,
    price_range: '₹800 - ₹1,200',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy Blue', 'Maroon'],
    categories: { id: 'cat-convocation', name: 'Convocation (Gowns & Caps)', slug: 'convocation' },
    created_at: new Date(Date.now() - 1500000).toISOString(),
  },
  {
    id: 'prod-security-guard',
    name: 'Classic Security Guard Uniform Shirt',
    description: 'Professional security officer shirt featuring button-down epaulettes, reinforced collar, and dual buttoned chest pockets. Breathable and comfortable for long watch shifts.',
    category_id: 'cat-security',
    images: ['/images/category_school.png'],
    fabric: 'Premium Poly-Cotton Twill Weave',
    is_featured: true,
    is_visible: true,
    price_range: '₹320 - ₹450',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Light Blue', 'Navy Blue', 'Khaki'],
    categories: { id: 'cat-security', name: 'Security & Defence Uniforms', slug: 'security' },
    created_at: new Date(Date.now() - 1600000).toISOString(),
    customization_available: true,
    fabric_care: 'Machine wash warm, tumble dry low, warm iron.',
    bulk_discounts: [{ qty: 50, discount: '5% Off' }, { qty: 100, discount: '10% Off' }, { qty: 500, discount: '20% Off' }],
    delivery_timeline: '7-10 working days',
    gender: 'Unisex',
    price_min: 320,
    price_max: 450
  },
  {
    id: 'prod-security-trousers',
    name: 'Tactical Security Officer Cargo Pants',
    description: 'Heavy-duty tactical cargo trousers designed for security personnel. Features six spacious utility pockets, reinforced knees, and double-stitched belt loops.',
    category_id: 'cat-security',
    images: ['/images/category_school.png'],
    fabric: 'Heavy Duty Ripstop Cotton-Poly',
    is_featured: false,
    is_visible: true,
    price_range: '₹480 - ₹690',
    min_order_qty: 50,
    sizes: ['30', '32', '34', '36', '38', '40'],
    colors: ['Black', 'Navy Blue', 'Olive Drab'],
    categories: { id: 'cat-security', name: 'Security & Defence Uniforms', slug: 'security' },
    created_at: new Date(Date.now() - 1610000).toISOString(),
    customization_available: true,
    fabric_care: 'Machine wash cold, air dry recommended.',
    bulk_discounts: [{ qty: 50, discount: '5% Off' }, { qty: 100, discount: '12% Off' }, { qty: 500, discount: '22% Off' }],
    delivery_timeline: '8-12 working days',
    gender: 'Unisex',
    price_min: 480,
    price_max: 690
  },
  {
    id: 'prod-industrial-boiler',
    name: 'Heavy Duty Cotton Boiler Suit (Coverall)',
    description: 'Full-body industrial coverall boiler suit featuring heavy-duty brass double-zipper front, action back for flexibility, and multiple pockets for tools.',
    category_id: 'cat-industrial',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Heavy%20Duty%20Cotton%20Boiler%20Suit%20(Coverall).%20Full-body%20industrial%20coverall%20boiler%20suit%20featuring%20heavy-duty%20brass%20double-zipper%20front%2C%20action%20back%20for%20flexibility%2C%20and%20multiple%20pockets%20for%20tools.?width=800&height=600&nologo=true&seed=42"],
    fabric: '100% Heavy-Duty Cotton Drill',
    is_featured: true,
    is_visible: true,
    price_range: '₹650 - ₹950',
    min_order_qty: 30,
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Royal Blue', 'Orange', 'Navy Blue'],
    categories: { id: 'cat-industrial', name: 'Industrial & Factory Workwear', slug: 'industrial' },
    created_at: new Date(Date.now() - 1620000).toISOString(),
    customization_available: true,
    fabric_care: 'Hot wash safe, machine dry medium, heavy iron.',
    bulk_discounts: [{ qty: 50, discount: '8% Off' }, { qty: 100, discount: '15% Off' }, { qty: 500, discount: '25% Off' }],
    delivery_timeline: '10-15 working days',
    gender: 'Unisex',
    price_min: 650,
    price_max: 950
  },
  {
    id: 'prod-industrial-jacket',
    name: 'Reflective High-Visibility Work Jacket',
    description: 'Two-tone industrial work jacket with 3M reflective safety stripes. Designed for road construction, airport crew, and warehouse safety.',
    category_id: 'cat-industrial',
    images: ["https://image.pollinations.ai/prompt/Professional%20catalog%20photo%20of%20Reflective%20High-Visibility%20Work%20Jacket.%20Two-tone%20industrial%20work%20jacket%20with%203M%20reflective%20safety%20stripes.%20Designed%20for%20road%20construction%2C%20airport%20crew%2C%20and%20warehouse%20safety.?width=800&height=600&nologo=true&seed=42"],
    fabric: 'Durable Polyester with PU Lamination',
    is_featured: false,
    is_visible: true,
    price_range: '₹420 - ₹580',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Neon Yellow', 'Neon Orange'],
    categories: { id: 'cat-industrial', name: 'Industrial & Factory Workwear', slug: 'industrial' },
    created_at: new Date(Date.now() - 1630000).toISOString(),
    customization_available: true,
    fabric_care: 'Wash cold inside out, do not iron on reflective tape.',
    bulk_discounts: [{ qty: 50, discount: '5% Off' }, { qty: 100, discount: '10% Off' }, { qty: 500, discount: '20% Off' }],
    delivery_timeline: '7-10 working days',
    gender: 'Unisex',
    price_min: 420,
    price_max: 580
  },
  {
    id: 'prod-sports-jersey',
    name: 'Custom Dry-Fit Sublimated Sports Jersey',
    description: 'Lightweight, sweat-wicking athletic PE and team jersey. Fully customizable with sublimation print for team names, logos, and numbers.',
    category_id: 'cat-sports',
    images: ['/images/school_pe_tracksuit.svg'],
    fabric: '100% Interlock Dry-Fit Polyester',
    is_featured: true,
    is_visible: true,
    price_range: '₹250 - ₹390',
    min_order_qty: 50,
    sizes: ['YS', 'YM', 'S', 'M', 'L', 'XL'],
    colors: ['Blue & White', 'Red & Black', 'Green & Yellow'],
    categories: { id: 'cat-sports', name: 'Sports & PE Uniforms', slug: 'sports' },
    created_at: new Date(Date.now() - 1640000).toISOString(),
    customization_available: true,
    fabric_care: 'Machine wash cold, do not fabric soften, do not iron.',
    bulk_discounts: [{ qty: 50, discount: '10% Off' }, { qty: 100, discount: '18% Off' }, { qty: 500, discount: '30% Off' }],
    delivery_timeline: '10-12 working days',
    gender: 'Kids',
    price_min: 250,
    price_max: 390
  },
  {
    id: 'prod-sports-track',
    name: 'School / Team Sports Tracksuit Set',
    description: 'High-performance team track jacket and matching athletic pants set. Contrast panel details, zip pockets, and elastic waist for comfort.',
    category_id: 'cat-sports',
    images: ['/images/school_pe_tracksuit.svg'],
    fabric: 'Super-Poly Brushed Tricot',
    is_featured: false,
    is_visible: true,
    price_range: '₹580 - ₹850',
    min_order_qty: 40,
    sizes: ['YS', 'YM', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy & Gold', 'Black & Red', 'Green & White'],
    categories: { id: 'cat-sports', name: 'Sports & PE Uniforms', slug: 'sports' },
    created_at: new Date(Date.now() - 1650000).toISOString(),
    customization_available: true,
    fabric_care: 'Wash warm, tumble dry low, do not iron logo.',
    bulk_discounts: [{ qty: 50, discount: '5% Off' }, { qty: 100, discount: '12% Off' }, { qty: 500, discount: '22% Off' }],
    delivery_timeline: '8-14 working days',
    gender: 'Kids',
    price_min: 580,
    price_max: 850
  },
  {
    id: 'prod-banking-shirt',
    name: 'Formal Banking Micro-Stripe Shirt',
    description: 'Crisp formal office shirt designed for banking and financial service teams. Wrinkle-resistant finish ensures a neat corporate appearance all day.',
    category_id: 'cat-banking',
    images: ['/images/corporate_mens_blazer.png'],
    fabric: '60% Egyptian Cotton / 40% Polyester Poplin',
    is_featured: true,
    is_visible: true,
    price_range: '₹450 - ₹650',
    min_order_qty: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Sky Blue Stripe', 'Grey Stripe', 'Pink Stripe'],
    categories: { id: 'cat-banking', name: 'Banking & Finance Formals', slug: 'banking' },
    created_at: new Date(Date.now() - 1660000).toISOString(),
    customization_available: true,
    fabric_care: 'Machine wash warm, iron medium, dry-cleanable.',
    bulk_discounts: [{ qty: 50, discount: '5% Off' }, { qty: 100, discount: '10% Off' }, { qty: 500, discount: '20% Off' }],
    delivery_timeline: '7-10 working days',
    gender: 'Unisex',
    price_min: 450,
    price_max: 650
  },
  {
    id: 'prod-banking-skirt',
    name: "Women's Classic Formal Pencil Skirt",
    description: 'Elegant tailored formal pencil skirt featuring a neat back kick pleat and comfortable stretch panels. Ideal for front office and bank tellers.',
    category_id: 'cat-banking',
    images: ['/images/corporate_mens_blazer.png'],
    fabric: 'Poly-Viscose Stretch Gabardine',
    is_featured: false,
    is_visible: true,
    price_range: '₹480 - ₹680',
    min_order_qty: 50,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal Grey', 'Navy Blue', 'Black'],
    categories: { id: 'cat-banking', name: 'Banking & Finance Formals', slug: 'banking' },
    created_at: new Date(Date.now() - 1670000).toISOString(),
    customization_available: true,
    fabric_care: 'Dry clean recommended, or machine wash cold on delicate.',
    bulk_discounts: [{ qty: 50, discount: '5% Off' }, { qty: 100, discount: '10% Off' }, { qty: 500, discount: '20% Off' }],
    delivery_timeline: '7-12 working days',
    gender: 'Women',
    price_min: 480,
    price_max: 680
  },
  {
    id: 'prod-police-tunic',
    name: 'Paramilitary Ceremonial Khaki Tunic',
    description: 'Traditional police and paramilitary tunic featuring structured shoulders, golden button closures, and chest epaulettes.',
    category_id: 'cat-police',
    images: ['/images/advocate_coat.png'],
    fabric: 'Heavy Poly-Wool Suiting',
    is_featured: true,
    is_visible: true,
    price_range: '₹1,500 - ₹2,200',
    min_order_qty: 20,
    sizes: ['36', '38', '40', '42', '44', '46'],
    colors: ['Khaki', 'Dark Blue'],
    categories: { id: 'cat-police', name: 'Police & Paramilitary (Ceremonial)', slug: 'police' },
    created_at: new Date(Date.now() - 1680000).toISOString(),
    customization_available: true,
    fabric_care: 'Dry clean only. Do not wash at home.',
    bulk_discounts: [{ qty: 50, discount: '5% Off' }, { qty: 100, discount: '10% Off' }, { qty: 500, discount: '18% Off' }],
    delivery_timeline: '15-20 working days',
    gender: 'Men',
    price_min: 1500,
    price_max: 2200
  },
  {
    id: 'prod-police-lanyard',
    name: 'Ceremonial Braided Whistle Lanyard',
    description: 'High-quality braided ceremonial police and security whistle lanyard. Features brass clasp and durable woven silk-thread braids.',
    category_id: 'cat-police',
    images: ['/images/advocate_coat.png'],
    fabric: '100% Mercerized Braided Cord',
    is_featured: false,
    is_visible: true,
    price_range: '₹120 - ₹180',
    min_order_qty: 100,
    sizes: ['Standard Size'],
    colors: ['Red & Gold', 'Blue & Silver', 'All Gold'],
    categories: { id: 'cat-police', name: 'Police & Paramilitary (Ceremonial)', slug: 'police' },
    created_at: new Date(Date.now() - 1690000).toISOString(),
    customization_available: false,
    fabric_care: 'Hand wash cold, air dry.',
    bulk_discounts: [{ qty: 100, discount: '5% Off' }, { qty: 500, discount: '15% Off' }],
    delivery_timeline: '5-7 working days',
    gender: 'Unisex',
    price_min: 120,
    price_max: 180
  },
  {
    id: 'prod-fire-suit',
    name: 'Flame-Retardant Nomex Safety Suit',
    description: 'Certified flame-resistant safety suit (jacket and trousers) designed for firefighters and industrial safety teams. Heavy-duty heat barrier protection.',
    category_id: 'cat-fire',
    images: ['/images/corporate_mens_blazer.png'],
    fabric: '93% Nomex / 5% Kevlar / 2% Antistatic Blend',
    is_featured: true,
    is_visible: true,
    price_range: '₹3,500 - ₹5,500',
    min_order_qty: 10,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Dark Navy', 'Saffron Orange', 'Fire Red'],
    categories: { id: 'cat-fire', name: 'Fire & Safety Uniforms', slug: 'fire' },
    created_at: new Date(Date.now() - 1700000).toISOString(),
    customization_available: true,
    fabric_care: 'Industrial laundering recommended, do not use chlorine bleach.',
    bulk_discounts: [{ qty: 20, discount: '5% Off' }, { qty: 50, discount: '10% Off' }, { qty: 100, discount: '15% Off' }],
    delivery_timeline: '12-18 working days',
    gender: 'Unisex',
    price_min: 3500,
    price_max: 5500
  },
  {
    id: 'prod-safety-vest',
    name: 'Fluorescent Reflective Safety Vest (Class 2)',
    description: 'Lightweight safety vest featuring high-visibility neon color with double vertical and horizontal 3M reflective tape bands. Features front zip closure.',
    category_id: 'cat-fire',
    images: ['/images/corporate_mens_blazer.png'],
    fabric: 'Breathable Polyester Warp Knit Mesh',
    is_featured: false,
    is_visible: true,
    price_range: '₹90 - ₹150',
    min_order_qty: 100,
    sizes: ['Free Size', 'XL', 'XXL'],
    colors: ['Neon Lime', 'Neon Orange'],
    categories: { id: 'cat-fire', name: 'Fire & Safety Uniforms', slug: 'fire' },
    created_at: new Date(Date.now() - 1710000).toISOString(),
    customization_available: true,
    fabric_care: 'Machine wash cold, do not iron reflective panels.',
    bulk_discounts: [{ qty: 100, discount: '5% Off' }, { qty: 500, discount: '15% Off' }, { qty: 1000, discount: '25% Off' }],
    delivery_timeline: '5-7 working days',
    gender: 'Unisex',
    price_min: 90,
    price_max: 150
  },
  {
    id: 'prod-airline-pilot',
    name: 'Aviation Pilot Epaulette Shirt',
    description: 'Crisp, high-performance pilot shirt. Features shoulder loops for epaulettes, dual mitred chest pockets with pencil slot, and durable interlined collars.',
    category_id: 'cat-airline',
    images: ['/images/corporate_mens_blazer.png'],
    fabric: '65% Polyester / 35% Combed Cotton Twill',
    is_featured: true,
    is_visible: true,
    price_range: '₹550 - ₹750',
    min_order_qty: 30,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Pristine White', 'Sky Blue'],
    categories: { id: 'cat-airline', name: 'Airline & Aviation Crew', slug: 'airline' },
    created_at: new Date(Date.now() - 1720000).toISOString(),
    customization_available: true,
    fabric_care: 'Machine wash warm, bleach safe for white, warm iron.',
    bulk_discounts: [{ qty: 50, discount: '5% Off' }, { qty: 100, discount: '10% Off' }, { qty: 500, discount: '20% Off' }],
    delivery_timeline: '7-10 working days',
    gender: 'Men',
    price_min: 550,
    price_max: 750
  },
  {
    id: 'prod-airline-hostess',
    name: 'Aviation Cabin Crew Blazer & Scarf Set',
    description: 'Elegant tailored crew blazer matching structured corporate pants/skirt, accessorized with a custom silk scarf. Professional, sleek look.',
    category_id: 'cat-airline',
    images: ['/images/corporate_mens_blazer.png'],
    fabric: 'Superfine Poly-Viscose Gabardine with Silk Scarf',
    is_featured: true,
    is_visible: true,
    price_range: '₹2,200 - ₹3,500',
    min_order_qty: 30,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Aviation Blue', 'Deep Burgundy', 'Classic Black'],
    categories: { id: 'cat-airline', name: 'Airline & Aviation Crew', slug: 'airline' },
    created_at: new Date(Date.now() - 1730000).toISOString(),
    customization_available: true,
    fabric_care: 'Dry clean only, iron on low temperature.',
    bulk_discounts: [{ qty: 50, discount: '5% Off' }, { qty: 100, discount: '12% Off' }, { qty: 500, discount: '22% Off' }],
    delivery_timeline: '10-15 working days',
    gender: 'Women',
    price_min: 2200,
    price_max: 3500
  }
]

// Dynamically enrich mock products with default values if they are missing
MOCK_PRODUCTS.forEach(p => {
  if (p.customization_available === undefined) p.customization_available = true
  if (p.fabric_care === undefined) {
    if (p.category_id === 'cat-corporate' || p.category_id === 'cat-advocate') {
      p.fabric_care = 'Dry clean only. Iron on low heat.'
    } else {
      p.fabric_care = 'Machine wash warm. Tumble dry low. Do not iron on print.'
    }
  }
  if (p.delivery_timeline === undefined) p.delivery_timeline = '7-10 working days'
  if (p.bulk_discounts === undefined) {
    p.bulk_discounts = [
      { qty: 50, discount: '5% Off' },
      { qty: 100, discount: '10% Off' },
      { qty: 500, discount: '20% Off' }
    ]
  }
  if (p.gender === undefined) {
    const n = p.name.toLowerCase()
    if (n.includes('women') || n.includes('female') || n.includes('girls') || n.includes('lady')) {
      p.gender = 'Women'
    } else if (n.includes('men') || n.includes('boys')) {
      p.gender = 'Men'
    } else if (n.includes('school') || n.includes('pe ') || n.includes('sports')) {
      p.gender = 'Kids'
    } else {
      p.gender = 'Unisex'
    }
  }
  if (p.price_min === undefined) {
    if (p.price_range) {
      const parts = p.price_range.replace(/[^\d-]/g, '').split('-')
      p.price_min = parseInt(parts[0]) || 0
      p.price_max = parseInt(parts[1]) || p.price_min || 1000
    } else {
      p.price_min = 200
      p.price_max = 500
    }
  }
})

// Filter to only include the 5 main categories
const allowedCategories = ['cat-corporate', 'cat-hospitality', 'cat-medical', 'cat-industrial', 'cat-school']
const filteredMockProducts = MOCK_PRODUCTS.filter(p => allowedCategories.includes(p.category_id))

// Assign specific faceless images for corporate products, fallback to category image for others
const productImages = {
  'prod-corporate-1': '/images/mens_blazer.png',
  'prod-corporate-women-blazer': '/images/womens_blazer.png',
  'prod-corporate-2': '/images/nehru_jacket.png',
  'prod-corporate-3': '/images/oxford_shirt.png'
}

const categoryImages = {
  'cat-corporate': '/images/corporate_shirt.png',
  'cat-hospitality': '/images/hospitality_coat.png',
  'cat-medical': '/images/medical_scrubs.png',
  'cat-industrial': '/images/industrial_coverall.png',
  'cat-school': '/images/school_polo.png'
}

filteredMockProducts.forEach(p => {
  if (productImages[p.id]) {
    p.images = [productImages[p.id]]
  } else {
    p.images = [categoryImages[p.category_id]]
  }
})

MOCK_PRODUCTS.length = 0
MOCK_PRODUCTS.push(...filteredMockProducts)


module.exports = { MOCK_PRODUCTS };
